# Dependencies
gems:
  - jekyll-pandoc

markdown:         Pandoc
pygments:         true

pandoc:
  extensions:
    - normalize
    - smart
    - csl: /Users/davidcolmenares/Imprenta/Styles/chicago-note-bibliography-16th-edition.csl.xml
    - bibliography: /Users/davidcolmenares/Documents/mylibraries/zoterotesis.bib
    
# Permalinks
permalink:        pretty

# Setup
title:            Anagogias
tagline:          'Fragments and figments'
description:      'This is the notebook of <a href="http://laic.columbia.edu/author/0987654321/" target="_blank">David Horacio Colmenares</a>.'
url:              http://hipomenes.github.io

author:
  name:           'David H. Colmenares'
  url:            https://twitter.com/dhcolmenares

paginate:         5

# Custom vars
version:          2.0

github:
  repo:           https://github.com/poole/lanyon
