# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Anagogias
tagline:          'Fragments and figments'
description:      'This is the personal blog of <a href="https://twitter.com/dhcolmenares" target="_blank">DH Colmenares</a>. Design by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hipomenes.github.io

author:
  name:           'DH Colmenares'
  url:            https://twitter.com/dhcolmenares

paginate:         5

# Custom vars
version:          2.0

github:
  repo:           https://github.com/poole/lanyon
